version: '2.3'

services:
  cfp-backend:
    container_name: cfp-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=4000
    ports:
      - '4000:4000'

  cfp-frontend:
    container_name: cfp-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
